language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: bellingard-github

script: 
#  - echo $SONARQUBE_SCANNER_PARAMS
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true sonar:sonar -Dsonar.host.url=https://fab.eu.ngrok.io

install: true

sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
