language: java

jdk:
  - oraclejdk8

add-on:
  sonarqube
    organization: bellingard-github

script: 
  - echo $SONAR_SCANNER_PARAMS
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true

install: true

sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
