language: java

addons:
  sonarcloud:
    organization: fab-test-travis

script: 
  - mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.test.failure.ignore=true

install: true

sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
