language: java

addons:
  sonarcloud:
    organization: bellingard-github
    token:
      secure: "MigdDJQBWlRmlXcyRwxwmr4pSOf1UF+KokOsQlAR9mq4mujNQXy5+N/frgOOmGw8m4wCcfZp/c955Es38SnI1w8GKKWCkXHF9ba7SF49D5lcQK4cW1HMCxC0O621iv2rbf6ehwiY8PhBRovia5aaM+Rb1BMvYYdVmPUcJ+0MFeU="

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.test.failure.ignore=true

install: true

sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
